# Generated by Django 4.2.16 on 2025-08-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_issue_latitude_issue_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('pipe_damage', 'Pipe Damage'), ('tap_failure', 'Tap Failure'), ('tank_empty', 'Tank Empty'), ('illegal_connection', 'Illegal Connection'), ('water_leak', 'Water Leak'), ('no_water_supply', 'No Water Supply'), ('contaminated_water', 'Contaminated Water'), ('broken_meter', 'Broken Water Meter'), ('low_pressure', 'Low Water Pressure'), ('unauthorized_use', 'Unauthorized Water Use'), ('sewage_overflow', 'Sewage Overflow'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed')], default='received', max_length=20),
        ),
    ]
