# Generated by Django 4.2.16 on 2025-08-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_issue_issue_type_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=10),
        ),
    ]
